[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "mediapipe>=0.10.21",
    "openai>=1.95.1",
    "opencv-python>=4.11.0.86",
    "streamlit>=1.46.1",
]
